repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
        exclude: ^notebooks/
      - id: debug-statements
        exclude: ^notebooks/
      - id: check-yaml
      - id: check-ast
        exclude: ^notebooks/
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML==6.0.3"]
        pass_filenames: false
        args: ["."]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        exclude: ^notebooks/
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-azure-pipelines
        files: azure_devops/.*\.yaml$
